import React from 'react';
import { Language, SUPPORTED_LANGUAGES, createTranslator, setStoredLanguage } from './i18n';

type ProfileProps = { language: Language; onLanguageChange: (language: Language) => void; onBack?: () => void };

export default function Profile({ language, onLanguageChange, onBack }: ProfileProps) {
  const t = createTranslator(language);
  const copy: Record<Language, {preferences:string; rules:string; rulesText:string; openRules:string; privacy:string; contact:string; contactText:string}> = {
    ru:{preferences:'Настройки',rules:'Правила использования',rulesText:'Используйте Bookly для законной деятельности и предоставляйте точную информацию о бизнесе, услугах и записи.',openRules:'Открыть правила',privacy:'Конфиденциальность',contact:'Контакты',contactText:'По вопросам работы Bookly и поддержки:'},
    en:{preferences:'Preferences',rules:'Rules of use',rulesText:'Use Bookly for legitimate business activity and provide accurate information about your business, services and bookings.',openRules:'Open rules',privacy:'Privacy',contact:'Contact',contactText:'For Bookly questions and support:'},
    uz:{preferences:'Sozlamalar',rules:'Foydalanish qoidalari',rulesText:'Bookly’dan qonuniy biznes faoliyati uchun foydalaning va biznes, xizmatlar hamda bronlar haqida aniq ma’lumot bering.',openRules:'Qoidalarni ochish',privacy:'Maxfiylik',contact:'Aloqa',contactText:'Bookly bo‘yicha savollar va yordam:'},
    tr:{preferences:'Tercihler',rules:'Kullanım kuralları',rulesText:'Bookly’yi yasal iş faaliyetleri için kullanın ve işletme, hizmetler ve rezervasyonlar hakkında doğru bilgiler sağlayın.',openRules:'Kuralları aç',privacy:'Gizlilik',contact:'İletişim',contactText:'Bookly soruları ve destek için:'},
    ar:{preferences:'التفضيلات',rules:'قواعد الاستخدام',rulesText:'استخدم Bookly لنشاط تجاري مشروع وقدّم معلومات دقيقة عن نشاطك وخدماتك وحجوزاتك.',openRules:'فتح القواعد',privacy:'الخصوصية',contact:'التواصل',contactText:'لأسئلة Bookly والدعم:'},
  };
  const c = copy[language];

  return (
    <section className="profile-page">
      <style>{`.profile-page{padding:10px 0 110px}.profile-back{margin:0 0 12px!important}.profile-hero{display:flex;align-items:center;gap:14px;padding:20px!important;background:linear-gradient(135deg,#fff,#f7f7fb);border:1px solid #e8e9ee;box-shadow:0 10px 32px rgba(15,23,42,.06)}.profile-avatar{width:54px;height:54px;border-radius:17px;background:#111;color:#fff;display:grid;place-items:center;font-size:24px;font-weight:850;box-shadow:0 8px 20px rgba(17,17,17,.12)}.profile-hero h1{font-size:28px!important;margin:0 0 4px!important;letter-spacing:-.8px!important}.profile-hero p{margin:0!important;color:#7a818b!important;font-size:12px!important}.profile-settings,.profile-info-card{border:1px solid #e7eaee!important;box-shadow:0 8px 28px rgba(15,23,42,.045)!important}.profile-settings h2,.profile-info-card h2{margin:0 0 12px;font-size:18px;letter-spacing:-.4px}.profile-card-label{font-size:10px;font-weight:850;letter-spacing:.13em;text-transform:uppercase;color:#8b919b;margin-bottom:7px}.profile-rule-copy{font-size:13px;color:#6e757f;line-height:1.55;margin:0 0 13px}.profile-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.profile-action{display:flex!important;align-items:center;justify-content:center;text-decoration:none!important;background:#111!important;color:#fff!important;border-radius:13px!important;padding:12px 10px!important;font-size:12px;font-weight:800}.profile-action.secondary{background:#fff!important;color:#111!important;border:1px solid #dfe3e8!important}.profile-contact{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid #eef0f2}.profile-contact span{color:#7c838d;font-size:12px}.profile-contact a{color:#111;text-decoration:none;font-size:12px;font-weight:800;word-break:break-word}@media(max-width:420px){.profile-actions{grid-template-columns:1fr}.profile-contact{display:block}.profile-contact a{display:block;margin-top:5px}}`}</style>
      {onBack && <button className="back profile-back" onClick={onBack}>← {t('common.back')}</button>}
      <div className="profile-hero card"><div className="profile-avatar">B</div><div><h1>{t('nav.profile')}</h1><p>Bookly</p></div></div>
      <div className="card profile-settings"><h2>{c.preferences}</h2><div className="profile-card-label">Language</div><div className="language-list">{SUPPORTED_LANGUAGES.map(item => { const active = item.code === language; return <button key={item.code} className={`language-option${active ? ' active' : ''}`} dir={item.dir} onClick={() => { setStoredLanguage(item.code); onLanguageChange(item.code); }}><span>{item.code === 'ru' && '🇷🇺 '}{item.code === 'en' && '🇬🇧 '}{item.code === 'uz' && '🇺🇿 '}{item.code === 'tr' && '🇹🇷 '}{item.code === 'ar' && '🇸🇦 '}{item.nativeLabel}</span>{active && <span>✓</span>}</button>; })}</div></div>
      <div className="card profile-info-card"><div className="profile-card-label">Bookly</div><h2>{c.rules}</h2><p className="profile-rule-copy">{c.rulesText}</p><div className="profile-actions"><a className="profile-action" href="/rules.html" target="_blank" rel="noreferrer">{c.openRules}</a><a className="profile-action secondary" href="/privacy.html" target="_blank" rel="noreferrer">{c.privacy}</a></div></div>
      <div className="card profile-info-card"><div className="profile-card-label">Bookly</div><h2>{c.contact}</h2><p className="profile-rule-copy">{c.contactText}</p><div className="profile-contact"><span>Email</span><a href="mailto:booklyminiapp@gmail.com">booklyminiapp@gmail.com</a></div></div>
    </section>
  );
}
