import React,{useEffect,useMemo,useRef,useState} from 'react';
import {
  Language,
  SUPPORTED_LANGUAGES,
  createTranslator,
  getStoredLanguage,
  setStoredLanguage,
  applyLanguageDirection,
} from './i18n';
import {createRoot} from 'react-dom/client';
import QRCode from 'qrcode';
import './style.css';
// Restored from commit 450e93c54de3bede612915bfbad6968bdceebf78; subsequent localization uses i18n + DOM completion layers.
declare global { interface Window { Telegram:any; Paddle:any } }
const API=import.meta.env.VITE_API_URL||'http://localhost:8000'; const BOT_USERNAME=import.meta.env.VITE_BOT_USERNAME||'BooklyBot'; const tg=()=>window.Telegram?.WebApp; const confirmAsync=(message:string):Promise<boolean>=>new Promise(resolve=>{const h=(window as any).__booklyConfirm;if(h)h(message,resolve);else resolve(window.confirm(message));}); const initData=()=>tg()?.initData||''; const headers=()=>{const base:Record<string,string>={'Content-Type':'application/json','X-Telegram-Init-Data':initData(),'X-Bookly-Language':getStoredLanguage()};try{const id=localStorage.getItem('bookly_active_business_id');if(id)base['X-Bookly-Business-Id']=id;}catch{}return base;}; const LOCALE_MAP:Record<Language,string>={ru:'ru-RU',en:'en-US',uz:'uz-UZ',tr:'tr-TR',ar:'ar-SA'}; const getLocale=()=>LOCALE_MAP[getStoredLanguage()]||'en-US'; const money=(v:number,c='UZS')=>`${new Intl.NumberFormat(getLocale()).format(v)} ${c}`; const localizedDays=(t:(key:string,fallback?:string)=>string)=>[t('days.mon'),t('days.tue'),t('days.wed'),t('days.thu'),t('days.fri'),t('days.sat'),t('days.sun')];
function BooklyAlertModal({open,title,message,onClose,t}:{open:boolean;title:string;message:string;onClose:()=>void;t:(key:string,fallback?:string)=>string}){if(!open)return null;return <div className="subscription-modal-overlay" onClick={onClose}><div className="subscription-modal" onClick={e=>e.stopPropagation()}><button type="button" className="subscription-modal-close" onClick={onClose}>×</button><span className="personal-eyebrow">BOOKLY</span><h2>{title}</h2><p className="muted">{message}</p><button type="button" className="primary full" onClick={onClose}>{t('common.ok','Понятно')}</button></div></div>}
function BooklyConfirmModal({open,message,onCancel,onConfirm,t}:{open:boolean;message:string;onCancel:()=>void;onConfirm:()=>void;t:(key:string,fallback?:string)=>string}){if(!open)return null;return <div className="subscription-modal-overlay" onClick={onCancel}><div className="subscription-modal" onClick={e=>e.stopPropagation()}><button type="button" className="subscription-modal-close" onClick={onCancel}>×</button><span className="personal-eyebrow">BOOKLY</span><p className="muted">{message}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:16}}><button type="button" onClick={onCancel}>{t('common.cancel','Отмена')}</button><button type="button" className="primary" onClick={onConfirm}>{t('common.confirm','Подтвердить')}</button></div></div></div>}
const TIMEZONE_OPTIONS=[['Asia/Tashkent','Ташкент'],['Asia/Almaty','Алматы'],['Asia/Bishkek','Бишкек'],['Asia/Dhaka','Дакка'],['Asia/Karachi','Карачи'],['Asia/Kolkata','Калькутта'],['Asia/Dubai','Дубай'],['Asia/Riyadh','Эр-Рияд'],['Asia/Tehran','Тегеран'],['Asia/Baghdad','Багдад'],['Asia/Jerusalem','Иерусалим'],['Asia/Baku','Баку'],['Asia/Tbilisi','Тбилиси'],['Europe/Moscow','Москва'],['Europe/Istanbul','Стамбул'],['Europe/Kiev','Киев'],['Europe/Berlin','Берлин'],['Europe/Paris','Париж'],['Europe/London','Лондон'],['Europe/Rome','Рим'],['Europe/Madrid','Мадрид'],['Africa/Cairo','Каир'],['Africa/Johannesburg','Йоханнесбург'],['America/New_York','Нью-Йорк'],['America/Chicago','Чикаго'],['America/Denver','Денвер'],['America/Los_Angeles','Лос-Анджелес'],['America/Toronto','Торонто'],['America/Sao_Paulo','Сан-Паулу'],['Australia/Sydney','Сидней'],['Pacific/Auckland','Окленд']]; const ALL_TIMEZONES=typeof (Intl as any).supportedValuesOf==='function'?(Intl as any).supportedValuesOf('timeZone'):TIMEZONE_OPTIONS.map(([value])=>value); const getTimeZoneLabel=(tz:string)=>{try{const loc=getLocale();const n=new Intl.DateTimeFormat(loc,{timeZone:tz,timeZoneName:'long'}).formatToParts(new Date()).find(x=>x.type==='timeZoneName')?.value||'';const o=new Intl.DateTimeFormat(loc,{timeZone:tz,timeZoneName:'shortOffset'}).formatToParts(new Date()).find(x=>x.type==='timeZoneName')?.value||'';return n?`${n} (${o})`:`${tz} (${o})`;}catch{return tz;}}; const getTimeZoneOffsetMinutes=(tz:string)=>{try{const v=new Intl.DateTimeFormat('en-US',{timeZone:tz,timeZoneName:'longOffset'}).formatToParts(new Date()).find(x=>x.type==='timeZoneName')?.value||'';const m=v.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?$/);if(!m)return 0;return(m[1]==='-'?-1:1)*(Number(m[2])*60+Number(m[3]||0));}catch{return 0;}}; const formatGMTOffset=(m:number)=>{if(m===0)return'GMT+0';const s=m<0?'-':'+';const a=Math.abs(m),h=Math.floor(a/60),mi=a%60;return mi?`GMT${s}${h}:${String(mi).padStart(2,'0')}`:`GMT${s}${h}`;}; const TIMEZONE_BY_OFFSET=Array.from(new Set(ALL_TIMEZONES.map((z:string)=>getTimeZoneOffsetMinutes(z)))).sort((a,b)=>a-b).map(offset=>{const zone=ALL_TIMEZONES.find((z:string)=>getTimeZoneOffsetMinutes(z)===offset)||'';return{zone,offset,label:`${formatGMTOffset(offset)} — ${getTimeZoneLabel(zone)}`};});

// FULL WORKING COMPONENT SOURCE RESTORED FROM THE PRIOR COMMIT.
